### PR TITLE
Added tab symbol into the game

### PR DESCRIPTION
**Pull request by GibberishDev**
Added asstest for Tab symbos as it doesnt have normal texture in original minecraft(for dumping nbt of items into chat)
How it looking now:
image
How i chnaged it to be:
image

### CODE REVIEW

**Comment by blackd** [comment]
It doesn't work for me. Does this require any other mods to actually show?

**Comment by GibberishDev** [comment]
Geeez, sorry. I was drunk i think and this was some random commit i decided to do for whatever reason.
I would just say what to do
Lemme fix(I now obliged to do so) that. In a meanwhile here is just a resource pack with fix
[tab.zip](https://github.com/blackd/Inventory-Profiles/files/7769253/tab.zip)

**Comment by GibberishDev** [comment]
P.S. everything should work now. My mistake was that while drunk I placed defaul.json at wrong directory.
Technically it is two mistakes one being file and other opening github while drunk ;)

**Comment by blackd** [comment]
This is the most constructive drunkenness I've seen in my life :rofl:

**Pull request merged**
