### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by GodGun968**

### CODE REVIEW

**Comment by GodGun968** [comment]
With so many settings, are you considering adding a search?

**Comment by blackd** [comment]
It's not that simple... So may be.

**Comment by GodGun968** [comment]
Haha, but the options really dazzle me, I often can't find some of them

**Comment by GodGun968** [comment]
hmm, it looks like everything is working, can you merge it?

**Comment by blackd** [comment]
I'll mege it before next release. Because I have local changes and I want to avoid conflicts.

**Pull request merged**
