### PR TITLE
Fix Modrinth download badge

### PR DESCRIPTION
**Pull request by triphora**
v1 of Modrinth's API has been deprecated since January 2022 and is scheduled to begin breaking in February, with a complete breakage being done by March. This pull request has been created as a courtesy to update it to use the dedicated shields.io badge rather than manually constructing the API request.

After merging this PR, please also update any usages on other pages, for example a CurseForge and/or Modrinth project description, and also cherry-pick/copy these changes to any other branches you might have.

### CODE REVIEW

**Comment by blackd** [comment]
I don't like that the new values is abbreviated.

**Comment by blackd** [comment]
So I will probably do something on my own that shows the full value or remove the Modrinth badge.
Depending on what time I have to spare.

**Comment by triphora** [comment]
I could revert it to the old way of doing things but update it to API v2, if the precise count is required for it to be merged. Just do note that, in the future, it will be necessary to update it again once API v2 gets replaced with v3, v3 with v4, etc... but it's not likely to be more than a once or twice a year sort of thing,

**Comment by triphora** [comment]
Also, the GitHub badge doesn't use a precise count. So it's pretty inconsistent that MR and CF have it but GH doesn't.

**Pull request merged**
