### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by GodGun968**
If possible, when adding new text to en_us.json also add new text to other language files

### CODE REVIEW

**Comment by blackd** [comment]
> If possible, when adding new text to en_us.json also add new text to other language files

it should be automatic but rarely works

**Comment by GodGun968** [comment]
In fact, it doesn't work at all, at least I don't see any results

**Comment by blackd** [comment]
it requires manual check if it's correct.

I may try to automate it better

**Comment by GodGun968** [comment]
I expect better, otherwise the translation job is really not easy

**Comment by blackd** [comment]
take a look here 
https://crowdin.com/project/inventry-profiles-next/

**Comment by GodGun968** [comment]
in the future, I only just submit it here?

**Comment by blackd** [comment]
yes or if you want your name to be attached to the commit use the site export it and submit PR

**Comment by GodGun968** [comment]
okay, at first I didn't find this, you should put this link in a prominent location

**Comment by GodGun968** [comment]
:P

**Comment by GodGun968** [comment]
I took a look, The json exported from here is not the same as the json format of github

**Comment by blackd** [comment]
the content is the same just sorted and formatted differently

**Comment by GodGun968** [comment]
So, if it is exported and uploaded to github, doesn't it match the original sorted and format.

**Comment by GodGun968** [comment]
It will cause it to be different from en_us.json

**Comment by blackd** [comment]
it matches en_us sorting

**Comment by GodGun968** [comment]
I mean, it won't be neat like this anymore
image

**Comment by GodGun968** [comment]
Well, it doesn't seem to matter

**Comment by blackd** [comment]
ah this can be done in the IDE.. at leas InteliJ Idea

**Comment by GodGun968** [comment]
How to do it

**Comment by blackd** [comment]
[2022-10-16 10-36-21.webm](https://user-images.githubusercontent.com/333840/196024132-dbbbbe7f-7e33-4777-9459-2ce4f459b2b1.webm)

**Comment by GodGun968** [comment]
oh ,thx

**Pull request merged**
