### PR TITLE
Create ko_kr.json

### PR DESCRIPTION
**Pull request by ssolephant**
I translated it because I want to support the mod
I checked that the translation was applied without any problems   
here doesn't seem to be any conflict, but I'd appreciate it if you could check it   
Thanks for answering my question on Discord before😌

PS. If anyone wants to add/change ko_kr translation later, u can change it right away without asking me
But if u need help, write a comment or send me a msg!
(PS. 나중에 한국어 번역을 추가/수정하고 싶으신 분이 있다면 저에게 묻지 않고 바로 변경하셔도 돼유
하지만 도움이 필요하시다면 코멘트나 메세지를 보내주세요!)

### CODE REVIEW

**Comment by blackd** [comment]
Hi,

Thank you for the translation :)
Just out of curiosity. Do you, somehow, get the folder names translated on checkout?

**Comment by ssolephant** [comment]
I'm not sure if I understood correctly, so I'll give you some answers...🥺   
1. How did you translate the folder name?   
The folder name written in the mod description was written as it is without translation   
This is because the folder name is used as it is without translation even in Korea   
2. Is there a way to translate the folder name?   
I don't think there is any way to translate the folder name. For file names, you can find the translation name you want here.   
https://minecraft.fandom.com/wiki/Language   
   
I'm sorry if I couldn't give you the answer you wanted    
If you tell me a little differently, I will try to check again and answer correctly😊

**Comment by blackd** [comment]
your commit has the folder names translated

`공유 소스/소스/기본/자원/자산/인벤토리 프로필다음/랭/`

instead of 

`shared-sources/src/main/resources/assets/inventoryprofilesnext/lang`

**Comment by ssolephant** [comment]
holy moly!!🤯
I was never aware of the change in the folder name of the folder😂😂😂
I think it's an error caused by the automatic translation of Chrome
I'll change it right away I'm sorry!

**Comment by blackd** [comment]
Hi,

Have you checked the translation tool I'm trying to use https://crowdin.com/project/inventry-profiles-next

Also there are some new strings that are 1.19.3 specific if you have time :)

**Pull request merged**
